const LANDING_SERVICE = process.env.NEXT_PUBLIC_ADMIN_SERVICE_URL
const PRODUCT_SERVICE = process.env.NEXT_PUBLIC_ADMIN_PRODUCT_URL
const CUSTOMER_SERVICE = process.env.NEXT_PUBLIC_ADMIN_CUSTOMER_URL

const GATEWAY_GUIDE_SERVICE = `${process.env.NEXT_PUBLIC_ADMIN_GATEWAY_URL}/guide-service`
const GATEWAY_CUSTOMER_SERVICE = `${process.env.NEXT_PUBLIC_ADMIN_GATEWAY_URL}/customer-service`
const GATEWAY_PLACE_SERVICE = `${process.env.NEXT_PUBLIC_ADMIN_GATEWAY_URL}/place-service`
const GATEWAY_USER_SERVICE = `${process.env.NEXT_PUBLIC_ADMIN_GATEWAY_URL}/user-service`
const GATEWAY_CLASSROOM_SERVICE = `${process.env.NEXT_PUBLIC_ADMIN_GATEWAY_URL}/classroom-service`
const GATEWAY_ACCOUNTING_SERVICE = `${process.env.NEXT_PUBLIC_ADMIN_GATEWAY_URL}/accounting-service`
const GATEWAY_PRODUCT_SERVICE = `${process.env.NEXT_PUBLIC_ADMIN_GATEWAY_URL}/product-service`

export {
  LANDING_SERVICE,
  PRODUCT_SERVICE,
  CUSTOMER_SERVICE,
  GATEWAY_GUIDE_SERVICE,
  GATEWAY_CUSTOMER_SERVICE,
  GATEWAY_PLACE_SERVICE,
  GATEWAY_USER_SERVICE,
  GATEWAY_CLASSROOM_SERVICE,
  GATEWAY_ACCOUNTING_SERVICE,
  GATEWAY_PRODUCT_SERVICE,
}
