export const mock = {
  content: [
    {
      id: 1,
      title: 'MenuCloudLabs',
      description: 'Versión inicial',
      active: true,
      version: '1.0',
    },
    {
      id: 2,
      title: 'MenuCloudLabs',
      description: 'CloudLabs Menú',
      active: false,
      version: '1.2',
    },
    {
      id: 3,
      title: 'MenuCloudLabs',
      description: 'Mejora visualización en teléfonos y corrige pinga Google (cambia a Server)',
      active: false,
      version: '3.0',
    },
    {
      id: 4,
      title: 'MenuCloudLabs',
      description: 'Menú sin selector de idioma',
      active: false,
      version: '4.0',
    },
    {
      id: 5,
      title: 'MenuCloudLabs',
      description: 'Mejoras generales',
      active: false,
      version: '4.5',
    },
    {
      id: 6,
      title: 'MenuCloudLabs',
      description: 'Descarga de facturas electronica',
      active: false,
      version: '6.0',
    },
    {
      id: 7,
      title: 'MenuCloudLabs',
      description: 'Nueva versión de menú 7.0',
      active: false,
      version: '7.0',
    },
  ],
  pageable: {
    sort: {
      sorted: false,
      unsorted: true,
      empty: true,
    },
    pageNumber: 0,
    pageSize: 10,
    offset: 0,
    paged: true,
    unpaged: false,
  },
  totalElements: 7,
  last: false,
  totalPages: 1,
  sort: {
    sorted: false,
    unsorted: true,
    empty: true,
  },
  numberOfElements: 10,
  first: true,
  size: 10,
  number: 0,
  empty: false,
}
